
//create a user 
POST http://localhost:5000/users

Content-Type :application/json 

{
    "name":"imen",
    "lastname":"romdhane",
    "address":"sousse",
    "telephone":"20055621",
    "email":"imen@gmail.com",
    "password" :"12345678",
    "confPassword": "12345678",
    "role":"secretaire"
}

****
//get all users
GET  http://localhost:5000/users

****

//get single user
GET  http://localhost:5000/users/69b2f6fb-b8f6-400f-844b-03339a8aa198

****
//update user 
PATCH  http://localhost:5000/users/31371429-cc00-4938-9a51-7acdcdb57c3e

Content-Type :application/json 
{
    "name":"imen2",
    "lastname":"romdhane",
    "address":"sousse",
    "telephone":"20055621",
    "email":"imen@gmail.com",
    "password" :"12345678",
    "confPassword": "12345678",
    "role":"secretaire"
}

****
//delete user 
DELETE http://localhost:5000/users/5ec81080-b52e-459d-9231-4000039f95b8

****
//Login user 

POST http://localhost:5000/login

Content-Type :application/json 

{
   
    "email":"admin@gmail.com",
    "password" :"123456"
  
}
*****

POST http://localhost:5000/login

Content-Type :application/json 

{  
    "email":"john@gmail.com",
    "password" :"123456"
    
}
*****
//Me

GET http://localhost:5000/me

*****
//logout
DELETE http://localhost:5000/logout

*******
//ajout fiche patient 
POST http://localhost:5000/fichePatient

{
    "name":"patient",
    "lastname":"romdhane",
    "telephone":"20055621",
    "email":"patient@gmail.com",
    "address":"sousse",
    "sexe":"homme",
    "dateNaiss":"1985-05-20",
    "numSecuriteSoc":"1234567890123"
    
    
   
}
*********
//get toutes FichePatient 

http://localhost:5000/fichePatient

************
//getSingle fichePatient 

http://localhost:5000/fichePatient/277f1549-1e46-44c1-b45b-6e391535898d

********
//update fiche patient 
http://localhost:5000/fichePatient/277f1549-1e46-44c1-b45b-6e391535898d

{
    "name":"patientTest",
    "lastname":"romdhaneTest",
    "telephone":"20055622",
    "email":"patient@gmail.com",
    "address":"sousse",
    "sexe":"homme",
    "dateNaiss":"1985-05-22",
    "numSecuriteSoc":"1234567890123"
    
}
*****************************
//delete fichePatient 

http://localhost:5000/fichePatient/1a75ea29-7c38-4bf7-809b-474a9ad21317